package me.onyxiansoul.onyxiancoreapi.actions;

import java.util.HashMap;
import java.util.Map;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.event.Event;

/**
 Actions are automatically generated by the plugin, following the instructions of the action type laid out in the config.
 */
public interface Action {
    
}
